# Generated by Django 5.1.4 on 2024-12-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusermaster',
            name='username',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='username',
        ),
    ]
